// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OnlineShop.db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220601202833_AddFirstData")]
    partial class AddFirstData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineShop.db.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.db.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("OnlineShop.db.Models.FavoriteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FavoriteProductId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Cost = 50000m,
                            Description = "Тур в Турцию за 50000 рублей",
                            ImagePath = "/images/turkey.jpg",
                            IsActive = true,
                            Name = "Тур в Турцию"
                        },
                        new
                        {
                            Id = -2,
                            Cost = 60000m,
                            Description = "Тур в Грецию за 60000 рублей",
                            ImagePath = "/images/greece.jpg",
                            IsActive = true,
                            Name = "Тур в Грецию"
                        },
                        new
                        {
                            Id = -3,
                            Cost = 45000m,
                            Description = "Тур в Болгарию за 45000 рублей",
                            ImagePath = "/images/bulgary.jpg",
                            IsActive = true,
                            Name = "Тур в Болгарию"
                        },
                        new
                        {
                            Id = -4,
                            Cost = 50000m,
                            Description = "Тур на Арубу за 50000 рублей",
                            ImagePath = "/images/aruba.jpg",
                            IsActive = true,
                            Name = "Тур на Арубу"
                        },
                        new
                        {
                            Id = -5,
                            Cost = 60000m,
                            Description = "Тур в Мексику за 60000 рублей",
                            ImagePath = "/images/mexico.jpg",
                            IsActive = true,
                            Name = "Тур в Мексику"
                        },
                        new
                        {
                            Id = -6,
                            Cost = 45000m,
                            Description = "Тур на Бали за 45000 рублей",
                            ImagePath = "/images/bali.jpg",
                            IsActive = true,
                            Name = "Тур на Бали"
                        },
                        new
                        {
                            Id = -7,
                            Cost = 50000m,
                            Description = "Тур в Еипет за 50000 рублей",
                            ImagePath = "/images/egypt.jpg",
                            IsActive = true,
                            Name = "Тур в Египет"
                        },
                        new
                        {
                            Id = -8,
                            Cost = 60000m,
                            Description = "Тур в ОАЭ за 60000 рублей",
                            ImagePath = "/images/uae.jpg",
                            IsActive = true,
                            Name = "Тур в ОАЭ"
                        },
                        new
                        {
                            Id = -9,
                            Cost = 45000m,
                            Description = "Тур на Сейшельские острова за 45000 рублей",
                            ImagePath = "/images/seyshels.jpg",
                            IsActive = true,
                            Name = "Тур на Сейшельские острова"
                        },
                        new
                        {
                            Id = -10,
                            Cost = 50000m,
                            Description = "Тур на Мальдивские острова за 50000 рублей",
                            ImagePath = "/images/jamaica.jpg",
                            IsActive = true,
                            Name = "Тур на Ямайку"
                        },
                        new
                        {
                            Id = -11,
                            Cost = 60000m,
                            Description = "Тур в Индию за 60000 рублей",
                            ImagePath = "/images/india.jpg",
                            IsActive = true,
                            Name = "Тур в Индию"
                        },
                        new
                        {
                            Id = -12,
                            Cost = 45000m,
                            Description = "Тур в Таиланд за 45000 рублей",
                            ImagePath = "/images/thailand.jpg",
                            IsActive = true,
                            Name = "Тур в Таиланд"
                        });
                });

            modelBuilder.Entity("OnlineShop.db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.db.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.db.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.db.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.db.Models.Customer", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.db.Models.FavoriteProduct", null)
                        .WithMany("Products")
                        .HasForeignKey("FavoriteProductId");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.db.Models.FavoriteProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
