// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.db;

#nullable disable

namespace OnlineShop.db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineShop.db.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.db.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineShop.db.Models.FavoriteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Url = "/images/turkey.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Url = "/images/greece.jpg"
                        },
                        new
                        {
                            Id = -3,
                            ProductId = -3,
                            Url = "/images/bulgary.jpg"
                        },
                        new
                        {
                            Id = -4,
                            ProductId = -4,
                            Url = "/images/aruba.jpg"
                        },
                        new
                        {
                            Id = -5,
                            ProductId = -5,
                            Url = "/images/mexico.jpg"
                        },
                        new
                        {
                            Id = -6,
                            ProductId = -6,
                            Url = "/images/bali.jpg"
                        },
                        new
                        {
                            Id = -7,
                            ProductId = -7,
                            Url = "/images/egypt.jpg"
                        },
                        new
                        {
                            Id = -8,
                            ProductId = -8,
                            Url = "/images/uae.jpg"
                        },
                        new
                        {
                            Id = -9,
                            ProductId = -9,
                            Url = "/images/seyshels.jpg"
                        },
                        new
                        {
                            Id = -10,
                            ProductId = -10,
                            Url = "/images/jamaica.jpg"
                        },
                        new
                        {
                            Id = -11,
                            ProductId = -11,
                            Url = "/images/india.jpg"
                        },
                        new
                        {
                            Id = -12,
                            ProductId = -12,
                            Url = "/images/thailand.jpg"
                        });
                });

            modelBuilder.Entity("OnlineShop.db.Models.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FavoriteProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 50000m,
                            Description = "Тур в Турцию за 50000 рублей",
                            IsActive = true,
                            Name = "Тур в Турцию"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 60000m,
                            Description = "Тур в Грецию за 60000 рублей",
                            IsActive = true,
                            Name = "Тур в Грецию"
                        },
                        new
                        {
                            Id = -3,
                            Cost = 45000m,
                            Description = "Тур в Болгарию за 45000 рублей",
                            IsActive = true,
                            Name = "Тур в Болгарию"
                        },
                        new
                        {
                            Id = -4,
                            Cost = 50000m,
                            Description = "Тур на Арубу за 50000 рублей",
                            IsActive = true,
                            Name = "Тур на Арубу"
                        },
                        new
                        {
                            Id = -5,
                            Cost = 60000m,
                            Description = "Тур в Мексику за 60000 рублей",
                            IsActive = true,
                            Name = "Тур в Мексику"
                        },
                        new
                        {
                            Id = -6,
                            Cost = 45000m,
                            Description = "Тур на Бали за 45000 рублей",
                            IsActive = true,
                            Name = "Тур на Бали"
                        },
                        new
                        {
                            Id = -7,
                            Cost = 50000m,
                            Description = "Тур в Еипет за 50000 рублей",
                            IsActive = true,
                            Name = "Тур в Египет"
                        },
                        new
                        {
                            Id = -8,
                            Cost = 60000m,
                            Description = "Тур в ОАЭ за 60000 рублей",
                            IsActive = true,
                            Name = "Тур в ОАЭ"
                        },
                        new
                        {
                            Id = -9,
                            Cost = 45000m,
                            Description = "Тур на Сейшельские острова за 45000 рублей",
                            IsActive = true,
                            Name = "Тур на Сейшельские острова"
                        },
                        new
                        {
                            Id = -10,
                            Cost = 50000m,
                            Description = "Тур на Мальдивские острова за 50000 рублей",
                            IsActive = true,
                            Name = "Тур на Ямайку"
                        },
                        new
                        {
                            Id = -11,
                            Cost = 60000m,
                            Description = "Тур в Индию за 60000 рублей",
                            IsActive = true,
                            Name = "Тур в Индию"
                        },
                        new
                        {
                            Id = -12,
                            Cost = 45000m,
                            Description = "Тур в Таиланд за 45000 рублей",
                            IsActive = true,
                            Name = "Тур в Таиланд"
                        });
                });

            modelBuilder.Entity("OnlineShop.db.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelegramUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OnlineShop.db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.db.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.db.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.db.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Image", b =>
                {
                    b.HasOne("OnlineShop.db.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.db.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.db.Models.FavoriteProduct", null)
                        .WithMany("Products")
                        .HasForeignKey("FavoriteProductId");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.db.Models.FavoriteProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.db.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
